### login
POST http://localhost:3000/auth/local/login
content-type: application/json

{"email": "22@22.com", "password": "asdlfkajsd"}

### Create a new user
POST http://localhost:3000/auth/local/register
content-type: application/json
{
  "email": "22@22.com",
  "password": "asdlfkajsd",
  "username": "123123"
}

### get user
GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiMjJAMjIuY29tIiwidHlwZSI6InVzZXIiLCJpYXQiOjE2NTQyODc5NDZ9.jHzuP0-AQHqxQGvVJF_qkvMPm50j2snB9OddDIZkQuc 


### Update a user
PATCH http://localhost:3000/user/1
content-type: application/json

{
  "password": "aaaaa"
}

### Find a particular user with a given ID
GET http://localhost:3000/user/2

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user given id
DELETE http://localhost:3000/auth/1

